gui:
  scrollHeight: 8
  theme:
    activeBorderColor:
      - '#FFA066'
      - bold
    inactiveBorderColor:
      - '#54546D'
    optionsTextColor:
      - '#8BA4B0'
    selectedLineBgColor:
      - '#2D4F67'
    cherryPickedCommitBgColor:
      - '#2A2A37'
    cherryPickedCommitFgColor:
      - '#8BA4B0'
      - bold
    unstagedChangesColor:
      - '#C4746E'
    defaultFgColor:
      - '#DCD7BA'
    searchingActiveBorderColor:
      - '#C8C093'

  authorColors:
    '*': '#b7bdf8'
git:
  pagers:
    - pager: diff-so-fancy
